CREATE DATABASE IF NOT EXISTS 'INFO',
USE info;

DROP TABLE IF EXISTS 'user';
CREATE TABLE IF NOT EXISTS 'user'(
    `Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(50) NOT NULL,
    `Email` VARCHAR(50) NOT NULL,
    `Username` VARCHAR(50) NOT NULL,
    `Password` VARCHAR(80) NOT NULL,
    'ImagePath' VARBINARY(MAX) NOT NULL,
    'Aboutme' VARCHAR(100) NOT NULL,
    PRIMARY KEY ('id')
) ;
